2023-06-15 21:31:21,115 [DEBUG] MainProcess(13386):MainThread        (4612373952) | emailall.run:69 - [*] Starting EmailAll @ 2023-06-15 21:31:21

2023-06-15 21:31:21,116 [INFOR] MainProcess(13386):MainThread        (4612373952) | utils.get_net_env:44 - Checking network environment
2023-06-15 21:31:21,116 [DEBUG] MainProcess(13386):MainThread        (4612373952) | utils.check_net:24 - Trying to access http://ip-api.com/json/
2023-06-15 21:31:21,495 [DEBUG] MainProcess(13386):MainThread        (4612373952) | utils.check_net:33 - Access to Internet OK
2023-06-15 21:31:21,496 [DEBUG] MainProcess(13386):MainThread        (4612373952) | utils.check_net:36 - The computer is located in China
2023-06-15 21:31:21,496 [DEBUG] MainProcess(13386):MainThread        (4612373952) | utils.get_domains:101 - Getting domains
2023-06-15 21:31:21,496 [DEBUG] MainProcess(13386):MainThread        (4612373952) | utils.get_domains:109 - The obtained domains 
['anker.com']
2023-06-15 21:31:21,496 [INFOR] MainProcess(13386):MainThread        (4612373952) | collect.run:45 - Start collecting Emails of anker.com
2023-06-15 21:31:22,062 [INFOR] MainProcess(13386):snov              (123145416937472) | module.begin:57 - Start Snov module to collect Emaile of anker.com
2023-06-15 21:31:22,063 [INFOR] MainProcess(13386):phonebook         (123145433726976) | module.begin:57 - Start PhoneBook module to collect Emaile of anker.com
2023-06-15 21:31:22,064 [INFOR] MainProcess(13386):skymem            (123145450516480) | module.begin:57 - Start Skymem module to collect Emaile of anker.com
2023-06-15 21:31:22,064 [INFOR] MainProcess(13386):Emailf            (123145467305984) | module.begin:57 - Start Email-Format module to collect Emaile of anker.com
2023-06-15 21:31:22,064 [INFOR] MainProcess(13386):veryvp            (123145484095488) | module.begin:57 - Start Veryvp module to collect Emaile of anker.com
2023-06-15 21:31:22,066 [INFOR] MainProcess(13386):bingcn            (123145500884992) | module.begin:57 - Start BingcnSearch module to collect Emaile of anker.com
2023-06-15 21:31:22,068 [INFOR] MainProcess(13386):ask               (123145517674496) | module.begin:57 - Start AskSearch module to collect Emaile of anker.com
2023-06-15 21:31:22,073 [INFOR] MainProcess(13386):githubapi         (123145534464000) | module.begin:57 - Start GithubApi module to collect Emaile of anker.com
2023-06-15 21:31:22,074 [INFOR] MainProcess(13386):google            (123145551253504) | module.begin:57 - Start GoogleSearch module to collect Emaile of anker.com
2023-06-15 21:31:22,077 [INFOR] MainProcess(13386):so                (123145568043008) | module.begin:57 - Start SoSearch module to collect Emaile of anker.com
2023-06-15 21:31:22,078 [INFOR] MainProcess(13386):sogou             (123145584832512) | module.begin:57 - Start SogouSearch module to collect Emaile of anker.com
2023-06-15 21:31:22,079 [INFOR] MainProcess(13386):baidu             (123145602695168) | module.begin:57 - Start BaiduSearch module to collect Emaile of anker.com
2023-06-15 21:31:22,079 [INFOR] MainProcess(13386):qwant             (123145619484672) | module.begin:57 - Start QwantSearch module to collect Emaile of anker.com
2023-06-15 21:31:23,528 [ERROR] MainProcess(13386):phonebook         (123145433726976) | module.post:132 - HTTPSConnectionPool(host='public.intelx.io', port=443): Max retries exceeded with url: /phonebook/search?k=077424c6-7a26-410e-9269-c9ac546886a4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7ff8106eab50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 21:31:23,528 [DEBUG] MainProcess(13386):phonebook         (123145433726976) | module.finish:66 - Finished PhoneBook module to collect anker.com's Email
2023-06-15 21:31:23,529 [INFOR] MainProcess(13386):phonebook         (123145433726976) | module.finish:68 - PhoneBook module took 1.5 seconds found 0 Email
2023-06-15 21:31:23,973 [DEBUG] MainProcess(13386):veryvp            (123145484095488) | module.finish:66 - Finished Veryvp module to collect anker.com's Email
2023-06-15 21:31:23,974 [INFOR] MainProcess(13386):veryvp            (123145484095488) | module.finish:68 - Veryvp module took 1.9 seconds found 0 Email
2023-06-15 21:31:24,474 [DEBUG] MainProcess(13386):Emailf            (123145467305984) | module.finish:66 - Finished Email-Format module to collect anker.com's Email
2023-06-15 21:31:24,474 [INFOR] MainProcess(13386):Emailf            (123145467305984) | module.finish:68 - Email-Format module took 2.4 seconds found 6 Email
2023-06-15 21:31:24,561 [DEBUG] MainProcess(13386):bingcn            (123145500884992) | module.finish:66 - Finished BingcnSearch module to collect anker.com's Email
2023-06-15 21:31:24,562 [INFOR] MainProcess(13386):bingcn            (123145500884992) | module.finish:68 - BingcnSearch module took 2.5 seconds found 0 Email
2023-06-15 21:31:24,569 [DEBUG] MainProcess(13386):baidu             (123145602695168) | module.finish:66 - Finished BaiduSearch module to collect anker.com's Email
2023-06-15 21:31:24,570 [INFOR] MainProcess(13386):baidu             (123145602695168) | module.finish:68 - BaiduSearch module took 2.5 seconds found 0 Email
2023-06-15 21:31:27,768 [ERROR] MainProcess(13386):qwant             (123145619484672) | module.get:102 - HTTPSConnectionPool(host='api.qwant.com', port=443): Read timed out. (read timeout=2)
2023-06-15 21:31:27,769 [DEBUG] MainProcess(13386):qwant             (123145619484672) | module.finish:66 - Finished QwantSearch module to collect anker.com's Email
2023-06-15 21:31:27,769 [INFOR] MainProcess(13386):qwant             (123145619484672) | module.finish:68 - QwantSearch module took 5.7 seconds found 0 Email
2023-06-15 21:31:28,666 [ALERT] MainProcess(13386):githubapi         (123145534464000) | utils.check_response:123 - GET https://api.github.com/search/code?q=anker.com&per_page=100&page=1&sort=indexed&access_token= 401 - Unauthorized 80
2023-06-15 21:31:28,666 [ALERT] MainProcess(13386):githubapi         (123145534464000) | utils.check_response:132 - {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}
2023-06-15 21:31:28,670 [ALERT] MainProcess(13386):githubapi         (123145534464000) | githubapi.search:72 - 'NoneType' object has no attribute 'json'
2023-06-15 21:31:28,670 [DEBUG] MainProcess(13386):githubapi         (123145534464000) | module.finish:66 - Finished GithubApi module to collect anker.com's Email
2023-06-15 21:31:28,670 [INFOR] MainProcess(13386):githubapi         (123145534464000) | module.finish:68 - GithubApi module took 6.6 seconds found 0 Email
2023-06-15 21:31:34,257 [DEBUG] MainProcess(13386):skymem            (123145450516480) | module.finish:66 - Finished Skymem module to collect anker.com's Email
2023-06-15 21:31:34,257 [INFOR] MainProcess(13386):skymem            (123145450516480) | module.finish:68 - Skymem module took 12.2 seconds found 25 Email
2023-06-15 21:31:42,144 [ERROR] MainProcess(13386):google            (123145551253504) | module.get:102 - HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff81071a070>, 'Connection to www.google.com timed out. (connect timeout=10)'))
2023-06-15 21:31:42,145 [ERROR] MainProcess(13386):google            (123145551253504) | google.search:41 - For module GoogleSearch, you need to configure the proxy in setting.py file
2023-06-15 21:31:42,146 [DEBUG] MainProcess(13386):google            (123145551253504) | module.finish:66 - Finished GoogleSearch module to collect anker.com's Email
2023-06-15 21:31:42,146 [INFOR] MainProcess(13386):google            (123145551253504) | module.finish:68 - GoogleSearch module took 20.1 seconds found 0 Email
2023-06-15 21:31:49,655 [ERROR] MainProcess(13386):sogou             (123145584832512) | module.get:102 - HTTPSConnectionPool(host='www.douyin.com', port=443): Read timed out. (read timeout=5)
2023-06-15 21:31:53,449 [ALERT] MainProcess(13386):sogou             (123145584832512) | utils.check_response:123 - GET https://ca.anker.com/pages/contact 404 - Not Found 9
2023-06-15 21:31:54,119 [ERROR] MainProcess(13386):ask               (123145517674496) | module.get:102 - HTTPSConnectionPool(host='www.ask.com', port=443): Max retries exceeded with url: /web?q=intext%3A%40anker.com&page=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff810702dc0>, 'Connection to www.ask.com timed out. (connect timeout=15)'))
2023-06-15 21:31:54,120 [ERROR] MainProcess(13386):ask               (123145517674496) | ask.search:44 - For module AskSearch, you need to configure the proxy in setting.py file
2023-06-15 21:31:54,120 [DEBUG] MainProcess(13386):ask               (123145517674496) | module.finish:66 - Finished AskSearch module to collect anker.com's Email
2023-06-15 21:31:54,120 [INFOR] MainProcess(13386):ask               (123145517674496) | module.finish:68 - AskSearch module took 32.1 seconds found 0 Email
2023-06-15 21:31:58,171 [ERROR] MainProcess(13386):sogou             (123145584832512) | module.get:102 - ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
2023-06-15 21:32:05,821 [ERROR] MainProcess(13386):sogou             (123145584832512) | module.get:102 - HTTPSConnectionPool(host='www.ankersingapore.com', port=443): Read timed out. (read timeout=5)
2023-06-15 21:32:11,478 [ERROR] MainProcess(13386):sogou             (123145584832512) | module.get:102 - HTTPSConnectionPool(host='www.8662.org', port=443): Read timed out. (read timeout=5)
2023-06-15 21:32:36,810 [ERROR] MainProcess(13386):sogou             (123145584832512) | module.get:102 - HTTPSConnectionPool(host='github.com', port=443): Read timed out. (read timeout=5)
2023-06-15 21:33:34,342 [ERROR] MainProcess(13386):sogou             (123145584832512) | module.get:102 - HTTPSConnectionPool(host='github.com', port=443): Max retries exceeded with url: /ankerapp/anker-app (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7ff810710700>, 'Connection to github.com timed out. (connect timeout=5)'))
2023-06-15 21:33:54,532 [ALERT] MainProcess(13386):so                (123145568043008) | utils.check_response:123 - GET https://www.price.com.hk/product.php?p=362479 403 - Forbidden 7793
2023-06-15 21:33:55,166 [ALERT] MainProcess(13386):so                (123145568043008) | utils.check_response:123 - GET https://www.price.com.hk/product.php?p=362479 403 - Forbidden 7816
2023-06-15 21:33:59,237 [ALERT] MainProcess(13386):so                (123145568043008) | utils.check_response:123 - GET https://www.ixigua.com/6999138441673835041 403 - Forbidden 0
2023-06-15 21:33:59,411 [ALERT] MainProcess(13386):so                (123145568043008) | utils.check_response:123 - GET https://www.ixigua.com/6999138441673835041 403 - Forbidden 0
2023-06-15 21:34:23,689 [ALERT] MainProcess(13386):sogou             (123145584832512) | utils.check_response:123 - GET https://zh.expansys.com.hk/audio/headphones/wireless/brand/anker/ 406 - Not Acceptable 1346
2023-06-15 21:34:25,168 [ALERT] MainProcess(13386):so                (123145568043008) | utils.check_response:123 - GET https://www.ixigua.com/6999138441673835041 403 - Forbidden 0
2023-06-15 21:34:25,328 [ALERT] MainProcess(13386):so                (123145568043008) | utils.check_response:123 - GET https://www.ixigua.com/6999138441673835041 403 - Forbidden 0
2023-06-15 21:34:25,861 [ALERT] MainProcess(13386):sogou             (123145584832512) | utils.check_response:123 - GET https://support.anker.com/s/ 401 - Unauthorized 0
2023-06-15 21:34:57,641 [ALERT] MainProcess(13386):so                (123145568043008) | utils.check_response:123 - GET https://www.price.com.hk/product.php?p=362479 403 - Forbidden 7816
2023-06-15 21:34:58,280 [ALERT] MainProcess(13386):so                (123145568043008) | utils.check_response:123 - GET https://www.price.com.hk/product.php?p=362479 403 - Forbidden 7794
2023-06-15 21:34:59,486 [ALERT] MainProcess(13386):so                (123145568043008) | utils.check_response:123 - GET https://www.ixigua.com/home/93090126552/ 403 - Forbidden 0
2023-06-15 21:34:59,609 [ALERT] MainProcess(13386):so                (123145568043008) | utils.check_response:123 - GET https://www.ixigua.com/home/93090126552/ 403 - Forbidden 0
2023-06-15 21:35:13,674 [DEBUG] MainProcess(13386):sogou             (123145584832512) | module.finish:66 - Finished SogouSearch module to collect anker.com's Email
2023-06-15 21:35:13,675 [INFOR] MainProcess(13386):sogou             (123145584832512) | module.finish:68 - SogouSearch module took 231.6 seconds found 6 Email
2023-06-15 21:37:54,117 [ALERT] MainProcess(13386):MainThread        (4612373952) | collect.run:64 - so module thread timed out
2023-06-15 22:23:10,559 [DEBUG] MainProcess(15511):MainThread        (4653374912) | emailall.run:69 - [*] Starting EmailAll @ 2023-06-15 22:23:10

2023-06-15 22:23:10,560 [INFOR] MainProcess(15511):MainThread        (4653374912) | utils.get_net_env:44 - Checking network environment
2023-06-15 22:23:10,560 [DEBUG] MainProcess(15511):MainThread        (4653374912) | utils.check_net:24 - Trying to access http://ip-api.com/json/
2023-06-15 22:23:11,051 [DEBUG] MainProcess(15511):MainThread        (4653374912) | utils.check_net:33 - Access to Internet OK
2023-06-15 22:23:11,051 [DEBUG] MainProcess(15511):MainThread        (4653374912) | utils.check_net:36 - The computer is located in China
2023-06-15 22:23:11,051 [DEBUG] MainProcess(15511):MainThread        (4653374912) | utils.get_domains:101 - Getting domains
2023-06-15 22:23:11,052 [DEBUG] MainProcess(15511):MainThread        (4653374912) | utils.get_domains:109 - The obtained domains 
['huawei.com']
2023-06-15 22:23:11,052 [INFOR] MainProcess(15511):MainThread        (4653374912) | collect.run:45 - Start collecting Emails of huawei.com
2023-06-15 22:23:11,610 [INFOR] MainProcess(15511):snov              (123145427468288) | module.begin:57 - Start Snov module to collect Emaile of huawei.com
2023-06-15 22:23:11,610 [INFOR] MainProcess(15511):phonebook         (123145444257792) | module.begin:57 - Start PhoneBook module to collect Emaile of huawei.com
2023-06-15 22:23:11,611 [INFOR] MainProcess(15511):skymem            (123145461047296) | module.begin:57 - Start Skymem module to collect Emaile of huawei.com
2023-06-15 22:23:11,612 [INFOR] MainProcess(15511):Emailf            (123145477836800) | module.begin:57 - Start Email-Format module to collect Emaile of huawei.com
2023-06-15 22:23:11,612 [INFOR] MainProcess(15511):veryvp            (123145494626304) | module.begin:57 - Start Veryvp module to collect Emaile of huawei.com
2023-06-15 22:23:11,615 [INFOR] MainProcess(15511):bingcn            (123145511415808) | module.begin:57 - Start BingcnSearch module to collect Emaile of huawei.com
2023-06-15 22:23:11,620 [INFOR] MainProcess(15511):ask               (123145528205312) | module.begin:57 - Start AskSearch module to collect Emaile of huawei.com
2023-06-15 22:23:11,622 [INFOR] MainProcess(15511):githubapi         (123145544994816) | module.begin:57 - Start GithubApi module to collect Emaile of huawei.com
2023-06-15 22:23:11,623 [INFOR] MainProcess(15511):google            (123145561784320) | module.begin:57 - Start GoogleSearch module to collect Emaile of huawei.com
2023-06-15 22:23:11,625 [INFOR] MainProcess(15511):so                (123145579646976) | module.begin:57 - Start SoSearch module to collect Emaile of huawei.com
2023-06-15 22:23:11,626 [INFOR] MainProcess(15511):sogou             (123145596436480) | module.begin:57 - Start SogouSearch module to collect Emaile of huawei.com
2023-06-15 22:23:11,627 [INFOR] MainProcess(15511):baidu             (123145613225984) | module.begin:57 - Start BaiduSearch module to collect Emaile of huawei.com
2023-06-15 22:23:11,628 [INFOR] MainProcess(15511):qwant             (123145630015488) | module.begin:57 - Start QwantSearch module to collect Emaile of huawei.com
2023-06-15 22:23:12,938 [ERROR] MainProcess(15511):phonebook         (123145444257792) | module.post:132 - HTTPSConnectionPool(host='public.intelx.io', port=443): Max retries exceeded with url: /phonebook/search?k=077424c6-7a26-410e-9269-c9ac546886a4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0eebac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:12,940 [DEBUG] MainProcess(15511):phonebook         (123145444257792) | module.finish:66 - Finished PhoneBook module to collect huawei.com's Email
2023-06-15 22:23:12,940 [INFOR] MainProcess(15511):phonebook         (123145444257792) | module.finish:68 - PhoneBook module took 1.3 seconds found 0 Email
2023-06-15 22:23:13,612 [ERROR] MainProcess(15511):bingcn            (123145511415808) | module.get:102 - Exceeded 30 redirects.
2023-06-15 22:23:13,613 [DEBUG] MainProcess(15511):bingcn            (123145511415808) | module.finish:66 - Finished BingcnSearch module to collect huawei.com's Email
2023-06-15 22:23:13,613 [INFOR] MainProcess(15511):bingcn            (123145511415808) | module.finish:68 - BingcnSearch module took 2.0 seconds found 0 Email
2023-06-15 22:23:13,990 [DEBUG] MainProcess(15511):baidu             (123145613225984) | module.finish:66 - Finished BaiduSearch module to collect huawei.com's Email
2023-06-15 22:23:13,991 [INFOR] MainProcess(15511):baidu             (123145613225984) | module.finish:68 - BaiduSearch module took 2.4 seconds found 0 Email
2023-06-15 22:23:14,217 [DEBUG] MainProcess(15511):Emailf            (123145477836800) | module.finish:66 - Finished Email-Format module to collect huawei.com's Email
2023-06-15 22:23:14,218 [INFOR] MainProcess(15511):Emailf            (123145477836800) | module.finish:68 - Email-Format module took 2.6 seconds found 49 Email
2023-06-15 22:23:15,011 [DEBUG] MainProcess(15511):veryvp            (123145494626304) | module.finish:66 - Finished Veryvp module to collect huawei.com's Email
2023-06-15 22:23:15,012 [INFOR] MainProcess(15511):veryvp            (123145494626304) | module.finish:68 - Veryvp module took 3.4 seconds found 0 Email
2023-06-15 22:23:18,274 [ALERT] MainProcess(15511):githubapi         (123145544994816) | utils.check_response:123 - GET https://api.github.com/search/code?q=huawei.com&per_page=100&page=1&sort=indexed&access_token= 401 - Unauthorized 80
2023-06-15 22:23:18,275 [ALERT] MainProcess(15511):githubapi         (123145544994816) | utils.check_response:132 - {'message': 'Bad credentials', 'documentation_url': 'https://docs.github.com/rest'}
2023-06-15 22:23:18,278 [ALERT] MainProcess(15511):githubapi         (123145544994816) | githubapi.search:72 - 'NoneType' object has no attribute 'json'
2023-06-15 22:23:18,279 [DEBUG] MainProcess(15511):githubapi         (123145544994816) | module.finish:66 - Finished GithubApi module to collect huawei.com's Email
2023-06-15 22:23:18,279 [INFOR] MainProcess(15511):githubapi         (123145544994816) | module.finish:68 - GithubApi module took 6.7 seconds found 0 Email
2023-06-15 22:23:25,047 [ERROR] MainProcess(15511):qwant             (123145630015488) | module.get:102 - HTTPSConnectionPool(host='api.qwant.com', port=443): Read timed out. (read timeout=2)
2023-06-15 22:23:25,050 [DEBUG] MainProcess(15511):qwant             (123145630015488) | module.finish:66 - Finished QwantSearch module to collect huawei.com's Email
2023-06-15 22:23:25,050 [INFOR] MainProcess(15511):qwant             (123145630015488) | module.finish:68 - QwantSearch module took 13.4 seconds found 9 Email
2023-06-15 22:23:27,179 [DEBUG] MainProcess(15511):skymem            (123145461047296) | module.finish:66 - Finished Skymem module to collect huawei.com's Email
2023-06-15 22:23:27,180 [INFOR] MainProcess(15511):skymem            (123145461047296) | module.finish:68 - Skymem module took 15.6 seconds found 25 Email
2023-06-15 22:23:27,461 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0eebd60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:27,511 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.huawei.com/cn/contact-us?tab=media (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0eebd00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:27,514 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.bilibili.com/read/cv17973575 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0eebe20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:27,517 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //consumer.huawei.com/minisite/worldwide/privacy-policy/cn/index.htm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0eeb040>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:27,520 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //e.huawei.com/cn/how-to-buy/contact-us (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0eebd00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:27,522 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www-ctc.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0eeb0d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:31,691 [ERROR] MainProcess(15511):google            (123145561784320) | module.get:102 - HTTPSConnectionPool(host='www.google.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f88e0f0ffd0>, 'Connection to www.google.com timed out. (connect timeout=10)'))
2023-06-15 22:23:31,691 [ERROR] MainProcess(15511):google            (123145561784320) | google.search:41 - For module GoogleSearch, you need to configure the proxy in setting.py file
2023-06-15 22:23:31,692 [DEBUG] MainProcess(15511):google            (123145561784320) | module.finish:66 - Finished GoogleSearch module to collect huawei.com's Email
2023-06-15 22:23:31,692 [INFOR] MainProcess(15511):google            (123145561784320) | module.finish:68 - GoogleSearch module took 20.1 seconds found 0 Email
2023-06-15 22:23:42,009 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //mail02.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f0fd00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:42,011 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.dz-z.com/list/huawei/12 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f0fd60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:42,013 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //dawhois.com/site/huawei.com.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f0f310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:42,015 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //developer.huawei.com/consumer/cn/hms/huawei-arengine/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f0fb80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:42,017 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.huawei.com/en/about-huawei/contact-us/index.htm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f0f9a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:42,018 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //developer.huawei.com/consumer/cn/vmall (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f0f040>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:44,359 [ERROR] MainProcess(15511):ask               (123145528205312) | module.get:102 - HTTPSConnectionPool(host='www.ask.com', port=443): Max retries exceeded with url: /web?q=intext%3A%40huawei.com&page=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f88e0fe62e0>, 'Connection to www.ask.com timed out. (connect timeout=15)'))
2023-06-15 22:23:44,359 [ERROR] MainProcess(15511):ask               (123145528205312) | ask.search:44 - For module AskSearch, you need to configure the proxy in setting.py file
2023-06-15 22:23:44,359 [DEBUG] MainProcess(15511):ask               (123145528205312) | module.finish:66 - Finished AskSearch module to collect huawei.com's Email
2023-06-15 22:23:44,360 [INFOR] MainProcess(15511):ask               (123145528205312) | module.finish:68 - AskSearch module took 32.7 seconds found 0 Email
2023-06-15 22:23:54,501 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //uniportal.huawei.com/uniportal/help_zh.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fdc850>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:54,504 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //intext.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fdc370>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:54,506 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //qingyun.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fdcb20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:54,509 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //m.ezkt.cn/siteinfo/26320.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fdc910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:23:54,511 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //m.ezkt.cn/siteinfo/26320.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fdcac0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:05,145 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.tuugo.hk/Companies/huawei-technologies/116000128382 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f0fa00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:05,147 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.intext.jp/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f0feb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:05,149 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //qingyun.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f0ffa0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:05,150 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.zpooo.com/ufws9991609.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f0f7f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:26,086 [ERROR] MainProcess(15511):so                (123145579646976) | module.get:102 - HTTPSConnectionPool(host='www.vmall.com', port=443): Max retries exceeded with url: /index.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f88e0fdc7c0>, 'Connection to www.vmall.com timed out. (connect timeout=5)'))
2023-06-15 22:24:26,641 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.chinait.com/label/%E5%8D%8E%E4%B8%BA?amp=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55400>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:26,644 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //blog.csdn.net/qq_44298324/article/details/122272212 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:26,646 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.thebigdata.cn/tag143.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55700>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:26,648 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //5gworkshops.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:26,650 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //support.huawei.com/enterprise/zh/intelligent-collaboration/te-webclient-pid-22019720/bulletins (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:26,652 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //wap.cnki.net/baozhi-RMYD20041021ZZ96.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55a30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:26,654 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //e.huawei.com/za/how-to-buy/contact-us (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:26,907 [ALERT] MainProcess(15511):so                (123145579646976) | utils.check_response:123 - GET https://www.51test.net/show/3538338.html 400 - Bad Request 146
2023-06-15 22:24:26,908 [ALERT] MainProcess(15511):so                (123145579646976) | utils.check_response:132 - {'code': 'MissingDateHeader', 'message': 'Request must have a "date" or "x-bce-date" header.', 'requestId': '5f0e08d3-6f88-4201-9789-26794e1093c6'}
2023-06-15 22:24:27,079 [ALERT] MainProcess(15511):so                (123145579646976) | utils.check_response:123 - GET https://www.51test.net/show/3538338.html 400 - Bad Request 146
2023-06-15 22:24:27,080 [ALERT] MainProcess(15511):so                (123145579646976) | utils.check_response:132 - {'code': 'MissingDateHeader', 'message': 'Request must have a "date" or "x-bce-date" header.', 'requestId': '46df7e12-c913-481d-b1e3-4f2711297fc6'}
2023-06-15 22:24:27,261 [ALERT] MainProcess(15511):so                (123145579646976) | utils.check_response:123 - GET https://www.51test.net/show/3538338.html 400 - Bad Request 146
2023-06-15 22:24:27,262 [ALERT] MainProcess(15511):so                (123145579646976) | utils.check_response:132 - {'code': 'MissingDateHeader', 'message': 'Request must have a "date" or "x-bce-date" header.', 'requestId': '3bffc5ad-49c3-4c9c-a228-c6c3b6cc5daf'}
2023-06-15 22:24:45,165 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.huawei.com/us/contact-us (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0febd60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:45,168 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //e.huawei.com/se/how-to-buy/contact-us (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0feb8b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:45,170 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //e.huawei.com/en/service-hotline (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0feb4f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:45,172 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //e.huawei.com/za/how-to-buy/contact-us (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c550a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:45,175 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.uedbox.com/shdb/68218/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55bb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:45,178 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.jemsdata.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55bb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:45,181 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.jemsdata.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55bb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:45,183 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.huawei.com/minisite/global-journey-of-antenna-modernization/summit.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55e20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:58,013 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.webmulu.com/search-url-www.huawei.com.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0feb340>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:58,018 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.webmulu.com/whois/huawei.com.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fce490>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:58,021 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.5gworkshops.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fce9a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:58,024 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //icp.aizhan.com/e.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fce550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:24:58,027 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //consumer.huawei.com/de/campaign/appgallery/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fceeb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:12,557 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.iyiou.com/company/huawei (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0edee80>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:12,559 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //forum.huawei.com/enterprise/thread-404103.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ede5b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:12,562 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //consumer.huawei.com/en/support/index.htm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ede700>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:12,565 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //github.com/Huawei (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0edea60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:12,567 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //blog.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ede190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:12,570 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.huaweicloud.com/intl/en-us/contact-sales.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ede4f0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:25,049 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //ca.urlm.com/www.huawei.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ede1c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:25,051 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //site.ip138.com/huaweicn.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ede520>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:25,053 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //blog.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ede7c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:25,054 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.yzdir.com/search-url-www.huawei.com.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ededf0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:25,057 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //data.danetsoft.com/consumer.huawei.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ede7c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:35,587 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //huawei.manymanuals.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f81670>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:35,589 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //support.huawei.com/enterprise/br/doc/EDOC1100011651/b0100f7e/huawei-ticket-submission-process (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f81c70>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:35,592 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //ip.911cha.com/huawei.com.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f81a00>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:35,594 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //forums.developer.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f810d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:46,121 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www-file.huawei.com/-/media/corporate/pdf/ilab/22-cn.pdf (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f81bb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:46,124 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //mshop.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f81190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:46,126 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //m.bilibili.com/video/BV1a34y127EW (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fce6a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:46,129 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.trustpilot.com/review/www.huawei.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fcee50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:25:51,331 [ERROR] MainProcess(15511):so                (123145579646976) | module.get:102 - HTTPConnectionPool(host='baike.so.com', port=80): Max retries exceeded with url: /doc/3755114-3944874.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f88e0fce400>, 'Connection to baike.so.com timed out. (connect timeout=5)'))
2023-06-15 22:25:53,602 [ERROR] MainProcess(15511):so                (123145579646976) | module.get:102 - Exceeded 30 redirects.
2023-06-15 22:25:55,867 [ERROR] MainProcess(15511):so                (123145579646976) | module.get:102 - Exceeded 30 redirects.
2023-06-15 22:26:00,644 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //shop.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c41df0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:00,647 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //mshop.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c41a30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:00,650 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.tomtop.com/jp/brands-huawei-2137/3.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c419a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:00,652 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.reviews.io/company-reviews/store/huawei-com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c41af0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:00,655 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //ask.dcloud.net.cn/people/391151 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c41970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:00,657 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.uedbox.com/shdb/60530/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c41d30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:13,232 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.tomtop.com/ru/brands-huawei-2137/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fe6e50>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:13,235 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.chinadaily.com.cn/china/2012-09/24/content_15779363.htm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fe6280>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:13,237 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.sjfzxm.com/global/fra/575229.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fe69a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:13,239 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.semrush.com/website/huawei.com/overview/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fe6760>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:13,242 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.sjfzxm.com/global/fra/146223.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0fe6df0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:25,748 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.g2a.com/search?query=Huawei (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1631a60>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:25,750 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.photodon.com/c/Huawei.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e16319d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:25,752 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.webmulu.com/site/12505.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1631970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:25,753 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //cn.club.vmall.com/forumuniversal-fid-3165-filter-typeid-orderby-dateline-typeid-10707.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1631760>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:25,755 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.sankedan.com/article/12/607502.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e16315e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:25,885 [ERROR] MainProcess(15511):so                (123145579646976) | module.get:102 - Exceeded 30 redirects.
2023-06-15 22:26:28,195 [ERROR] MainProcess(15511):so                (123145579646976) | module.get:102 - Exceeded 30 redirects.
2023-06-15 22:26:33,641 [ERROR] MainProcess(15511):so                (123145579646976) | module.get:102 - HTTPConnectionPool(host='baike.so.com', port=80): Max retries exceeded with url: /doc/3755114-3944874.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f88e0f5aa30>, 'Connection to baike.so.com timed out. (connect timeout=5)'))
2023-06-15 22:26:34,374 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //icp.aizhan.com/huawei-expo.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0edea90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:34,376 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //article.in3pid.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0edeee0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:34,380 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //app.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ede640>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:47,304 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.huaweiglobal.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0feb8b0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:47,306 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.tuugo.hk/Companies/huawei/116000137327 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0feb4c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:47,308 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.8662.org/huawei.com.cn.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0febcd0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:47,310 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.95mulu.com/siteinfo/51091.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0feba30>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:26:47,313 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.uenu.com/whois?domain=huawei.com.cn&lang=fr (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0febe20>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:03,856 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.dhgate.com/online-shopping/huawei-smart-mate-online.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c25f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:03,858 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //site.ip138.com/huaweileasing.com/whois.htm (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ef75e0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:03,860 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.huawei.com/cn/contact-us/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ef79d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:03,862 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //support.huawei.com/enterprise/zh/enterprise-communications/te-webclient-pid-22019720/bulletins (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ef71c0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:03,865 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //mtuiguang.chinaadmin.cn/url/e.huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ef7190>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:03,867 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //en.huaweifh.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ef79d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:03,870 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.cbi360.net/hhb/sg_362372/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0ef7970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:20,823 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //german.alibaba.com/Popular/CN_huawei-ascent-Trade.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f73550>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:20,826 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //support.huawei.com/enterprise/zh/network-management/esight-pid-9184477?category=learn-about-products (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f73a90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:20,829 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.prnewswire.com/news-releases/huawei-presente-sa-ligne-directrice-de-linfrastructure-tic-axee-sur-les-activites-commerciales-a-loccasion-du-huawei-network-congress-2015-504746971.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f73f40>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:20,832 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.yzdir.net/whois/huaweirom.com.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f73be0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:20,835 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.huaweicloud.com/service/contact.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f73eb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:20,838 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.biqudiao.com/11/27009178.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f73970>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:20,841 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.portugalglobal.pt/PT/InvestirPortugal/CasosSucesso/Paginas/Huawei.aspx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f73be0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:37,517 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttp', port=443): Max retries exceeded with url: //www.95mulu.com/siteinfo/25889.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e0f1b340>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:37,520 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //link.aizhan.com/huawei.com/ (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c553a0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:37,522 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //forum.xda-developers.com/t/official-huawei-ascend-thread.872608/page-50 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55be0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:37,524 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.8662.org/huawei.com.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c559d0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:37,526 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.chaxunle.cn/ip/partner.huawei.com.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55310>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:37,528 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.chaxunle.cn/ip/www.huawei.comwww.huawei.com.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55820>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:37,530 [ERROR] MainProcess(15511):sogou             (123145596436480) | module.get:102 - HTTPSConnectionPool(host='www.sogou.comhttps', port=443): Max retries exceeded with url: //www.docin.com/p-1374908423.html (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f88e1c55bb0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known'))
2023-06-15 22:27:37,533 [DEBUG] MainProcess(15511):sogou             (123145596436480) | module.finish:66 - Finished SogouSearch module to collect huawei.com's Email
2023-06-15 22:27:37,533 [INFOR] MainProcess(15511):sogou             (123145596436480) | module.finish:68 - SogouSearch module took 265.9 seconds found 0 Email
2023-06-15 22:29:20,950 [ERROR] MainProcess(15511):so                (123145579646976) | module.get:102 - HTTPConnectionPool(host='baike.so.com', port=80): Max retries exceeded with url: /doc/6411146-6624813.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f88e0edeb20>, 'Connection to baike.so.com timed out. (connect timeout=5)'))
2023-06-15 22:29:23,497 [ERROR] MainProcess(15511):so                (123145579646976) | module.get:102 - Exceeded 30 redirects.
2023-06-15 22:29:29,853 [ERROR] MainProcess(15511):so                (123145579646976) | module.get:102 - HTTPConnectionPool(host='baike.so.com', port=80): Max retries exceeded with url: /doc/6411146-6624813.html (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f88e160b040>, 'Connection to baike.so.com timed out. (connect timeout=5)'))
2023-06-15 22:29:41,356 [ERROR] MainProcess(15511):so                (123145579646976) | module.get:102 - Exceeded 30 redirects.
2023-06-15 22:29:43,596 [ERROR] MainProcess(15511):so                (123145579646976) | module.get:102 - Exceeded 30 redirects.
2023-06-15 22:29:44,358 [ALERT] MainProcess(15511):MainThread        (4653374912) | collect.run:64 - so module thread timed out
